# This is a basic workflow to help you get started with Actions

name: CBH-selenium-grid

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Starting Selenoid Server
      uses: ajinx/selenoid@2.0

    - name: Build with Maven
      run: mvn clean -DHOST=host.docker.selenium.grid -DBROWSER=chrome test
